export const GET_USER_DATA_LOGIN_LOADING = 'GET_USER_DATA_LOGIN_LOADING';
export const GET_USER_DATA_LOGIN_SUCCESS = 'GET_USER_DATA_LOGIN_SUCCESS';
export const GET_USER_DATA_LOGIN_ERROR = 'GET_USER_DATA_LOGIN_ERROR';

// добавляем новые картинки для портфолио
export const ADD_USER_PORTFOLIO_IMG_LOADING = 'ADD_USER_PORTFOLIO_IMG_LOADING';
export const ADD_USER_PORTFOLIO_IMG_SUCCESS = 'ADD_USER_PORTFOLIO_IMG_SUCCESS';
export const ADD_USER_PORTFOLIO_IMG_ERROR = 'ADD_USER_PORTFOLIO_IMG_ERROR';

// удаляем картинки из портфолио
export const DELETE_USER_PORTFOLIO_IMG_ERROR = 'DELETE_USER_PORTFOLIO_IMG_ERROR';
export const DELETE_USER_PORTFOLIO_IMG_SUCCESS = 'DELETE_USER_PORTFOLIO_IMG_SUCCESS';
export const DELETE_USER_PORTFOLIO_IMG_LOADING = 'DELETE_USER_PORTFOLIO_IMG_LOADING';

// первоночальная загрузка всех картинок для портфолио
export const GET_ALL_USER_PORTFOLIO_LOADING = 'GET_ALL_USER_PORTFOLIO_LOADING';
export const GET_ALL_USER_PORTFOLIO_SUCCESS = 'GET_ALL_USER_PORTFOLIO_SUCCESS';
export const GET_ALL_USER_PORTFOLIO_ERROR = 'GET_ALL_USER_PORTFOLIO_ERROR';
