export const GET_USER_DATA_LOGIN_LOADING = 'GET_USER_DATA_LOGIN_LOADING';
export const GET_USER_DATA_LOGIN_SUCCESS = 'GET_USER_DATA_LOGIN_SUCCESS';
export const GET_USER_DATA_LOGIN_ERROR = 'GET_USER_DATA_LOGIN_ERROR';

// добавляем новые картинки для портфолио
export const ADD_USER_PORTFOLIO_IMG_LOADING = 'ADD_USER_PORTFOLIO_IMG_LOADING';
export const ADD_USER_PORTFOLIO_IMG_SUCCESS = 'ADD_USER_PORTFOLIO_IMG_SUCCESS';
export const ADD_USER_PORTFOLIO_IMG_ERROR = 'ADD_USER_PORTFOLIO_IMG_ERROR';

// удаляем картинки из портфолио
export const DELETE_USER_PORTFOLIO_IMG_ERROR = 'DELETE_USER_PORTFOLIO_IMG_ERROR';
export const DELETE_USER_PORTFOLIO_IMG_SUCCESS = 'DELETE_USER_PORTFOLIO_IMG_SUCCESS';
export const DELETE_USER_PORTFOLIO_IMG_LOADING = 'DELETE_USER_PORTFOLIO_IMG_LOADING';

// первоночальная загрузка всех картинок для портфолио
export const GET_ALL_USER_PORTFOLIO_LOADING = 'GET_ALL_USER_PORTFOLIO_LOADING';
export const GET_ALL_USER_PORTFOLIO_SUCCESS = 'GET_ALL_USER_PORTFOLIO_SUCCESS';
export const GET_ALL_USER_PORTFOLIO_ERROR = 'GET_ALL_USER_PORTFOLIO_ERROR';

// проверяем авторизован ли пользователь
export const GET_USER_DATA_AUTH_LOADING = 'GET_USER_DATA_AUTH_LOADING';
export const GET_USER_DATA_AUTH_SUCCESS = 'GET_USER_DATA_AUTH_SUCCESS';
export const GET_USER_DATA_AUTH_ERROR = 'GET_USER_DATA_AUTH_ERROR';

// logout, удаляем куки и сессию
export const LOGOUT_USER_LOADING = 'LOGOUT_USER_LOADING';
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

// status service change
export const STATUS_SERVICE_CHANGE_LOADING = 'STATUS_SERVICE_CHANGE_LOADING';
export const STATUS_SERVICE_CHANGE_ERROR = 'STATUS_SERVICE_CHANGE_ERROR';
export const STATUS_SERVICE_CHANGE_SUCCESS = 'STATUS_SERVICE_CHANGE_SUCCESS';

// add about me description
export const ADD_DESCRIPTION_LOADING = 'ADD_DESCRIPTION_LOADING';
export const ADD_DESCRIPTION_ERROR = 'ADD_DESCRIPTION_ERROR';
export const ADD_DESCRIPTION_SUCCESS = 'ADD_DESCRIPTION_SUCCESS';

// add about me description SAGA
export const ADD_DESCRIPTION_SAGA_LOADING = 'ADD_DESCRIPTION_SAGA_LOADING';
export const ADD_DESCRIPTION_SAGA_ERROR = 'ADD_DESCRIPTION_SAGA_ERROR';
export const ADD_DESCRIPTION_SAGA_SUCCESS = 'ADD_DESCRIPTION_SAGA_SUCCESS';

// add my contacts
export const ADD_CONTACT_LOADING = 'ADD_CONTACT_LOADING';
export const ADD_CONTACT_ERROR = 'ADD_CONTACT_ERROR';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
